name: Build and Deploy PWA to Coolify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io  # or your registry
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/agrinote-pwa:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/agrinote-pwa:latest

      - name: Deploy to Coolify
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            -F "image=ghcr.io/${{ github.repository }}/agrinote-pwa:latest" \
            https://your-coolify-instance.com/api/deployments
